import Image from "next/image";
import Link from "next/link";
import Contact from "@/components/Contact";
import FAQAccordion from "@/components/FAQAccordion";

const content = {
  en: {
    hero: { eyebrow: "Independent security practice, Switzerland", title: "Prepare your organization for attacks that begin with trust.", body: "Practical social engineering training and focused penetration testing for organizations that need people and controls to perform under pressure.", primary: "Schedule a conversation", secondary: "View engagements" },
    risk: { eyebrow: "Human risk", title: "The first control an attacker tests is often a person.", body: ["An urgent payment request, a familiar voice or a routine login prompt can create the opening that technical controls were meant to prevent.", "Readiness comes from realistic practice, clear verification habits and a reporting path people can use when a decision feels urgent."] },
    services: {
      eyebrow: "Engagements", title: "Focused security work with a defined outcome.", intro: "Two focused offers cover the human and technical sides of exposure. Scope, delivery and the decision that follows are made explicit before the work begins.",
      items: [
        { label: "Primary engagement", title: "Social Engineering Readiness", text: "A focused program combining scenario-led training and role-specific simulations. It prepares teams for impersonation, voice-based attacks, MFA abuse, payment fraud, malware delivery and the decisions that make those attacks succeed.", result: "Teams practice how to recognize, verify and report manipulation under pressure.", path: "services/social-engineering-readiness", link: "Explore social engineering readiness" },
        { label: "Technical validation", title: "Penetration Testing", text: "Manual-first testing across web applications, APIs, external exposure, internal networks and Active Directory, with clear boundaries and reproducible evidence.", result: "Prioritized findings, remediation context and an optional retest.", path: "services/pentesting", link: "Explore penetration testing" },
      ],
    },
    principles: { eyebrow: "Working principles", title: ["Clear boundaries.", "Direct responsibility.", "Useful evidence."], items: [["Scope before activity", "Objectives, assets, participants, exclusions and decision criteria are explicit before testing or training begins."], ["Authorization without ambiguity", "Sensitive exercises require written authority, agreed contacts and a clear escalation path."], ["Direct specialist involvement", "The person who scopes the engagement remains involved in delivery, analysis and the final readout."], ["Outputs built for action", "Management receives clarity. Technical teams receive enough context and evidence to move forward."]] },
    about: { eyebrow: "About the practice", title: "Direct access to the person responsible for the work.", paragraphs: ["in7ruder is a founder-led security practice built around careful scoping, direct communication and personal responsibility for delivery.", "My background combines building web applications with studying how attackers abuse people, identity and technical weaknesses. That perspective keeps human behavior and technical controls connected in every engagement.", "Work stays intentionally focused. If a broader team is ever needed, that is made clear before the engagement begins."], founder: "Matias Vanarelli, Founder", link: "View background on LinkedIn", alt: "Matias Vanarelli, founder of in7ruder" },
    faqTitle: "Before we speak.", faqEyebrow: "Common questions",
    faqs: [["What types of teams do you train?", "Training can be designed for the wider organization or adapted to roles with greater exposure, including finance, executive support, IT, customer service and operations."], ["Can training reflect scenarios specific to our organization?", "Yes. The engagement begins with context. Scenarios are selected around relevant workflows, communication channels and threat patterns without exposing sensitive internal information unnecessarily."], ["How do you handle simulations and employee privacy?", "The purpose, authorization, data collected, reporting level and retention period are agreed before delivery. The default approach favors aggregated learning and practical improvement over individual blame."], ["What is included in a penetration test?", "The proposal defines the exact assets, methods, exclusions, testing window, reporting format and retest conditions. Findings include enough context and evidence for teams to reproduce, prioritize and remediate them."], ["Can we begin with a focused engagement?", "Yes. A workshop or tightly scoped assessment is often the right way to establish priorities and working fit before committing to a broader program."]],
  },
  de: {
    hero: { eyebrow: "Unabhängige Security-Boutique, Schweiz", title: "Bereiten Sie Ihr Unternehmen auf Angriffe vor, die mit Vertrauen beginnen.", body: "Praxisnahe Social-Engineering-Trainings und fokussierte Penetrationstests für Unternehmen, deren Mitarbeitende und Sicherheitskontrollen auch unter Druck funktionieren müssen.", primary: "Erstgespräch vereinbaren", secondary: "Leistungen ansehen" },
    risk: { eyebrow: "Faktor Mensch", title: "Die erste Sicherheitsbarriere, die Angreifer testen, ist oft ein Mensch.", body: ["Eine dringende Zahlungsaufforderung, eine vertraute Stimme oder eine routinemässige Anmeldeanfrage kann genau die Lücke schaffen, die technische Kontrollen verhindern sollten.", "Echte Bereitschaft entsteht durch realistische Übungen, klare Verifikationsroutinen und einen Meldeweg, der auch unter Zeitdruck funktioniert."] },
    services: {
      eyebrow: "Leistungen", title: "Fokussierte Sicherheitsarbeit mit einem klaren Ergebnis.", intro: "Zwei fokussierte Angebote decken die menschliche und die technische Angriffsfläche ab. Umfang, Durchführung und die anschliessende Entscheidung werden vor Beginn eindeutig festgelegt.",
      items: [
        { label: "Zentrales Angebot", title: "Social Engineering Readiness", text: "Ein fokussiertes Programm aus szenariobasiertem Training und rollenspezifischen Simulationen. Teams bereiten sich auf Identitätsmissbrauch, sprachbasierte Angriffe, MFA-Missbrauch, Zahlungsbetrug, Malware-Zustellung und die zugrunde liegenden Entscheidungen vor.", result: "Teams üben, Manipulation unter Druck zu erkennen, zu verifizieren und zu melden.", path: "services/social-engineering-readiness", link: "Social Engineering Readiness ansehen" },
        { label: "Technische Validierung", title: "Penetrationstest", text: "Manuell geführte Tests von Webanwendungen, APIs, externer Angriffsfläche, internen Netzwerken und Active Directory mit klaren Grenzen und reproduzierbaren Nachweisen.", result: "Priorisierte Findings, Kontext für die Behebung und ein optionaler Retest.", path: "services/pentesting", link: "Penetrationstests ansehen" },
      ],
    },
    principles: { eyebrow: "Arbeitsprinzipien", title: ["Klare Grenzen.", "Direkte Verantwortung.", "Nutzbare Evidenz."], items: [["Scope vor Aktivität", "Ziele, Systeme, Teilnehmende, Ausschlüsse und Entscheidungskriterien werden vor Training oder Tests eindeutig festgelegt."], ["Eindeutige Autorisierung", "Sensible Übungen erfordern eine schriftliche Freigabe, vereinbarte Kontakte und einen klaren Eskalationsweg."], ["Direkte Einbindung", "Die Person, die das Engagement definiert, bleibt an Durchführung, Analyse und Abschlussbesprechung beteiligt."], ["Ergebnisse für konkrete Massnahmen", "Das Management erhält Klarheit. Technische Teams erhalten ausreichend Kontext und Nachweise für die nächsten Schritte."]] },
    about: { eyebrow: "Über die Boutique", title: "Direkter Zugang zu der Person, die für die Arbeit verantwortlich ist.", paragraphs: ["in7ruder ist eine inhabergeführte Security-Boutique, die auf sorgfältigem Scoping, direkter Kommunikation und persönlicher Verantwortung für die Durchführung basiert.", "Mein Hintergrund verbindet die Entwicklung von Webanwendungen mit der Analyse, wie Angreifer Menschen, Identitäten und technische Schwachstellen ausnutzen. So bleiben menschliches Verhalten und technische Kontrollen in jedem Engagement miteinander verbunden.", "Die Arbeit bleibt bewusst fokussiert. Sollte ein grösseres Team erforderlich sein, wird dies vor Beginn des Engagements transparent gemacht."], founder: "Matias Vanarelli, Gründer", link: "Hintergrund auf LinkedIn ansehen", alt: "Matias Vanarelli, Gründer von in7ruder" },
    faqTitle: "Vor dem Gespräch.", faqEyebrow: "Häufige Fragen",
    faqs: [["Welche Teams trainieren Sie?", "Das Training kann für die gesamte Organisation konzipiert oder an besonders exponierte Rollen angepasst werden, darunter Finanzen, Executive Support, IT, Kundenservice und Operations."], ["Kann das Training unsere konkreten Szenarien berücksichtigen?", "Ja. Das Engagement beginnt mit dem Kontext. Szenarien werden anhand relevanter Abläufe, Kommunikationskanäle und Bedrohungsmuster ausgewählt, ohne sensible interne Informationen unnötig offenzulegen."], ["Wie gehen Sie mit Simulationen und der Privatsphäre von Mitarbeitenden um?", "Zweck, Autorisierung, erhobene Daten, Berichtsebene und Aufbewahrungsdauer werden vor der Durchführung vereinbart. Standardmässig stehen aggregiertes Lernen und praktische Verbesserung vor individueller Schuldzuweisung."], ["Was ist in einem Penetrationstest enthalten?", "Das Angebot definiert Systeme, Methoden, Ausschlüsse, Testfenster, Berichtsformat und Retest-Bedingungen. Findings enthalten ausreichend Kontext und Nachweise für Reproduktion, Priorisierung und Behebung."], ["Können wir mit einem fokussierten Engagement beginnen?", "Ja. Ein Workshop oder ein eng abgegrenzter Test ist häufig der richtige Weg, um Prioritäten und Zusammenarbeit zu prüfen, bevor ein grösseres Programm vereinbart wird."]],
  },
};

function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function HomePage({ lang }) {
  const copy = content[lang] || content.en;
  const home = `/${lang}`;
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "@id": `https://in7ruder.com/${lang}#faq`,
    mainEntity: copy.faqs.map(([question, answer]) => ({
      "@type": "Question",
      name: question,
      acceptedAnswer: { "@type": "Answer", text: answer },
    })),
  };
  return (
    <div id="main-content" lang={lang}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <section className="border-b border-[var(--line)] bg-[var(--paper)]"><div className="page-wrap py-16 md:py-24 lg:py-28"><p className="eyebrow">{copy.hero.eyebrow}</p><div className="mt-8 max-w-5xl"><h1 className="display-title serif-display">{copy.hero.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[var(--muted)] md:text-xl">{copy.hero.body}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={`${home}/#contact`} className="button-primary">{copy.hero.primary} <Arrow /></Link><Link href={`${home}/#services`} className="button-secondary">{copy.hero.secondary}</Link></div></div></div></section>

      <section className="bg-[var(--ink)] text-white"><div className="page-wrap py-16 md:py-24"><div className="max-w-4xl"><p className="eyebrow eyebrow-dark">{copy.risk.eyebrow}</p><h2 className="section-title serif-display mt-7">{copy.risk.title}</h2><div className="mt-9 grid gap-6 border-t border-white/20 pt-8 text-base leading-7 text-white/70 md:grid-cols-2 md:gap-12 md:text-lg md:leading-8">{copy.risk.body.map((item) => <p key={item}>{item}</p>)}</div></div></div></section>

      <section id="services" className="bg-[var(--paper)]"><div className="page-wrap py-16 md:py-24"><header className="max-w-3xl"><p className="eyebrow">{copy.services.eyebrow}</p><h2 className="section-title serif-display mt-7">{copy.services.title}</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">{copy.services.intro}</p></header><div className="mt-12 border-t border-[var(--ink)]">{copy.services.items.map((item) => <article key={item.title} className="engagement-row"><div><p className="eyebrow">{item.label}</p><h3 className="serif-display mt-4 text-3xl leading-tight md:text-4xl">{item.title}</h3></div><div><p className="text-base leading-7 text-[var(--muted)]">{item.text}</p><p className="mt-4 text-sm font-semibold leading-6 text-[var(--ink)]">{item.result}</p><Link href={`${home}/${item.path}`} className="text-link mt-6">{item.link} <Arrow /></Link></div></article>)}</div></div></section>

      <section id="approach" className="border-y border-[var(--line)] bg-[var(--accent-soft)] text-[var(--ink)]"><div className="page-wrap py-16 md:py-24"><header className="max-w-3xl"><p className="eyebrow">{copy.principles.eyebrow}</p><h2 className="principles-title serif-display mt-7">{copy.principles.title.map((line) => <span key={line}>{line}</span>)}</h2></header><div className="mt-12 border-t border-[var(--line)]">{copy.principles.items.map(([title, text]) => <article key={title} className="grid gap-3 border-b border-[var(--line)] py-7 md:grid-cols-[18rem_1fr] md:gap-12"><h3 className="font-semibold">{title}</h3><p className="max-w-2xl text-sm leading-7 text-[var(--muted)]">{text}</p></article>)}</div></div></section>

      <section id="about" className="bg-[var(--paper)]"><div className="page-wrap grid gap-10 py-16 md:py-24 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] lg:gap-16"><div className="relative min-h-[28rem] overflow-hidden bg-[#dedede] md:min-h-[38rem]"><Image src="/img/matias.JPG" alt={copy.about.alt} fill sizes="(min-width: 1024px) 42vw, 100vw" className="scale-[1.18] object-cover object-[center_24%]" /></div><div className="self-center"><p className="eyebrow">{copy.about.eyebrow}</p><h2 className="section-title serif-display mt-7">{copy.about.title}</h2><div className="mt-8 max-w-2xl space-y-5 text-base leading-8 text-[var(--muted)]">{copy.about.paragraphs.map((item) => <p key={item}>{item}</p>)}</div><p className="mt-7 font-semibold">{copy.about.founder}</p><a href="https://www.linkedin.com/in/mvanarelli/" target="_blank" rel="noreferrer" className="text-link mt-5">{copy.about.link} <Arrow /></a></div></div></section>

      <section className="border-y border-[var(--line)] bg-[var(--canvas)]"><div className="page-wrap grid gap-10 py-16 md:py-24 lg:grid-cols-[0.65fr_1.35fr] lg:gap-20"><header><p className="eyebrow">{copy.faqEyebrow}</p><h2 className="serif-display mt-7 text-4xl leading-tight md:text-5xl">{copy.faqTitle}</h2></header><FAQAccordion items={copy.faqs} /></div></section>
      <Contact lang={lang} />
    </div>
  );
}
