import Link from "next/link";
import FAQAccordion from "@/components/FAQAccordion";
import { alternatesFor, localizedUrl } from "@/lib/i18n";

const copyByLanguage = {
  en: {
    title: "Social Engineering Readiness", description: "Scenario-led social engineering training and authorized simulations that help teams recognize, verify and report manipulation under pressure.",
    hero: ["Social Engineering Readiness", "Prepare people for attacks built on trust.", "Practical training and authorized simulations that help teams recognize manipulation, verify unusual requests and report concerns before pressure becomes an incident.", "Discuss an engagement", "Explore the scope"],
    stats: [["Built for", "Teams exposed to high-trust, high-pressure decisions"], ["Methods", "Training, simulations, debriefs and response practice"], ["Outcome", "Clearer verification and reporting behavior"]],
    risk: ["Why readiness matters", "Attackers turn normal behavior into an attack surface.", "Trust, urgency, authority and routine help organizations function. They also create openings when a request looks familiar and a decision feels time sensitive.", "The goal is not to make employees suspicious of everything. It is to make verification and reporting easier when context changes or something does not feel right."],
    scope: ["Capability", "One program, shaped around the attacks that matter.", "The final scope depends on the audience, relevant threats and the decisions the organization needs people to handle more safely."],
    capabilities: [["Scenario-led training", "Live sessions use realistic decisions instead of generic awareness slides. Content is adapted to the roles, workflows and exposure of the audience."], ["Phishing and impersonation", "Authorized exercises can cover email, messaging, executive impersonation, supplier fraud and other pretexts relevant to the organization."], ["Voice and identity attacks", "Teams practice handling urgent calls, familiar voices, MFA requests and attempts to bypass verification through authority or pressure."], ["Malware delivery scenarios", "Safe demonstrations explain how malicious links, documents and payloads reach users, what warning signals matter and how to respond without creating unnecessary risk."]],
    formatsHeader: ["Engagement formats", "Start with the decision that needs to improve."],
    formats: [["Focused workshop", "A practical session for a defined team or risk scenario, followed by clear response guidance."], ["Readiness engagement", "Training, authorized simulation and debrief combined into a structured improvement cycle."], ["Role-specific exercise", "Targeted preparation for exposed functions such as finance, executive support, IT, operations or customer-facing teams."]],
    method: ["How the work is run", "Realistic enough to be useful. Controlled enough to be safe."],
    methodItems: [["Written authorization", "Audience, channels, scenarios, data handling, escalation contacts and safe stop conditions are agreed first."], ["Relevant pressure", "Exercises reflect genuine workflows without using humiliation, surprise or fear as teaching methods."], ["Practical debrief", "Participants understand the signals, decision points and reporting actions that matter after the exercise."], ["Management clarity", "Observations are translated into prioritized improvements, ownership and an appropriate next step."]],
    faqHeader: ["Common questions", "Before we define the scenario."],
    faqs: [["Is this standard security awareness training?", "No. The engagement is built around realistic scenarios, decisions and reporting paths that are relevant to your organization. It is not a generic compliance presentation."], ["Can phishing simulations be included?", "Yes. Simulations are one method inside the wider readiness engagement. Authorization, audience, data handling, escalation paths and reporting are agreed before delivery."], ["Do you identify individual employees in reports?", "The default approach favors aggregated learning and operational improvement. Any individual-level reporting must have a clear purpose and be explicitly agreed in advance."], ["Can the content be adapted to a specific team?", "Yes. Finance, executive support, IT, operations and customer-facing teams face different pretexts and decision pressure. Scenarios are selected accordingly."], ["What does management receive?", "A concise readout covering observed behavior, relevant gaps, recommended improvements and appropriate next steps. The goal is a decision-ready output, not a leaderboard."]],
    final: ["Start with context", "Build readiness around the situations your people actually face.", "Schedule a conversation"],
  },
  de: {
    title: "Social Engineering Readiness", description: "Szenariobasiertes Social-Engineering-Training und autorisierte Simulationen, mit denen Teams Manipulation unter Druck erkennen, verifizieren und melden.",
    hero: ["Social Engineering Readiness", "Bereiten Sie Menschen auf Angriffe vor, die auf Vertrauen bauen.", "Praxisnahes Training und autorisierte Simulationen helfen Teams, Manipulation zu erkennen, ungewöhnliche Anfragen zu verifizieren und Bedenken zu melden, bevor Druck zu einem Vorfall führt.", "Engagement besprechen", "Leistungsumfang ansehen"],
    stats: [["Geeignet für", "Teams mit vertrauensbasierten Entscheidungen unter hohem Zeitdruck"], ["Methoden", "Training, Simulationen, Debriefs und praktische Reaktionsübungen"], ["Ergebnis", "Besseres Verifikations- und Meldeverhalten"]],
    risk: ["Warum Bereitschaft zählt", "Angreifer machen normales Verhalten zur Angriffsfläche.", "Vertrauen, Dringlichkeit, Autorität und Routine ermöglichen effiziente Zusammenarbeit. Sie schaffen aber auch Lücken, wenn eine Anfrage vertraut wirkt und eine Entscheidung unter Zeitdruck fällt.", "Das Ziel ist nicht, Mitarbeitende gegenüber allem misstrauisch zu machen. Verifikation und Meldung sollen leichter werden, sobald sich der Kontext verändert oder etwas nicht stimmig wirkt."],
    scope: ["Leistungsumfang", "Ein Programm, ausgerichtet auf die relevanten Angriffe.", "Der konkrete Umfang richtet sich nach Zielgruppe, relevanten Bedrohungen und den Entscheidungen, die das Unternehmen sicherer gestalten möchte."],
    capabilities: [["Szenariobasiertes Training", "Live-Sessions nutzen realistische Entscheidungen statt allgemeiner Awareness-Folien. Inhalte werden an Rollen, Abläufe und Exposition der Zielgruppe angepasst."], ["Phishing und Identitätsvortäuschung", "Autorisierte Übungen können E-Mail, Messaging, Executive Impersonation, Lieferantenbetrug und weitere relevante Vorwände abdecken."], ["Sprach- und Identitätsangriffe", "Teams üben den Umgang mit dringenden Anrufen, vertrauten Stimmen, MFA-Anfragen und Versuchen, Verifikation durch Autorität oder Druck zu umgehen."], ["Szenarien zur Malware-Zustellung", "Sichere Demonstrationen zeigen, wie bösartige Links, Dokumente und Payloads Nutzende erreichen, welche Warnsignale zählen und wie ohne unnötiges Risiko reagiert wird."]],
    formatsHeader: ["Engagement-Formate", "Beginnen Sie mit der Entscheidung, die sich verbessern soll."],
    formats: [["Fokussierter Workshop", "Eine praxisnahe Session für ein definiertes Team oder Risikoszenario mit klarer Anleitung für die Reaktion."], ["Readiness Engagement", "Training, autorisierte Simulation und Debrief als strukturierter Verbesserungszyklus."], ["Rollenspezifische Übung", "Gezielte Vorbereitung exponierter Funktionen wie Finanzen, Executive Support, IT, Operations oder kundennaher Teams."]],
    method: ["Durchführung", "Realistisch genug, um nützlich zu sein. Kontrolliert genug, um sicher zu bleiben."],
    methodItems: [["Schriftliche Autorisierung", "Zielgruppe, Kanäle, Szenarien, Datenverarbeitung, Eskalationskontakte und Abbruchbedingungen werden zuerst vereinbart."], ["Relevanter Druck", "Übungen spiegeln reale Abläufe wider, ohne Bloßstellung, Überraschung oder Angst als Lehrmethode einzusetzen."], ["Praktisches Debrief", "Teilnehmende verstehen nach der Übung die relevanten Signale, Entscheidungspunkte und Meldewege."], ["Klarheit für das Management", "Beobachtungen werden in priorisierte Verbesserungen, Verantwortlichkeiten und einen passenden nächsten Schritt übersetzt."]],
    faqHeader: ["Häufige Fragen", "Bevor wir das Szenario definieren."],
    faqs: [["Ist das ein gewöhnliches Security-Awareness-Training?", "Nein. Das Engagement basiert auf realistischen Szenarien, Entscheidungen und Meldewegen, die für Ihr Unternehmen relevant sind. Es ist keine allgemeine Compliance-Präsentation."], ["Können Phishing-Simulationen enthalten sein?", "Ja. Simulationen sind eine Methode innerhalb des umfassenderen Readiness Engagements. Autorisierung, Zielgruppe, Datenverarbeitung, Eskalationswege und Reporting werden vorab vereinbart."], ["Werden einzelne Mitarbeitende in Berichten identifiziert?", "Standardmäßig stehen aggregiertes Lernen und operative Verbesserung im Vordergrund. Berichte auf Individualebene benötigen einen klaren Zweck und eine ausdrückliche vorherige Vereinbarung."], ["Können Inhalte an ein bestimmtes Team angepasst werden?", "Ja. Finanzen, Executive Support, IT, Operations und kundenahe Teams erleben unterschiedliche Vorwände und Entscheidungsdruck. Die Szenarien werden entsprechend ausgewählt."], ["Was erhält das Management?", "Ein kompaktes Readout mit beobachtetem Verhalten, relevanten Lücken, empfohlenen Verbesserungen und sinnvollen nächsten Schritten. Das Ergebnis dient Entscheidungen, nicht einer Rangliste."]],
    final: ["Mit Kontext beginnen", "Bauen Sie Bereitschaft für die Situationen auf, denen Ihre Mitarbeitenden tatsächlich begegnen.", "Erstgespräch vereinbaren"],
  },
};

function Arrow() { return <span aria-hidden="true">↗</span>; }

export async function generateMetadata({ params }) {
  const { lang } = await params;
  const copy = copyByLanguage[lang] || copyByLanguage.en;
  return { title: copy.title, description: copy.description, alternates: alternatesFor(lang, "services/social-engineering-readiness"), openGraph: { type: "website", locale: lang === "de" ? "de_CH" : "en_CH", url: localizedUrl(lang, "services/social-engineering-readiness"), siteName: "in7ruder", title: `${copy.title} | in7ruder`, description: copy.description } };
}

export default async function SocialEngineeringReadinessPage({ params }) {
  const { lang } = await params;
  const copy = copyByLanguage[lang] || copyByLanguage.en;
  const base = `/${lang}`;
  const jsonLd = { "@context": "https://schema.org", "@type": "Service", name: copy.title, description: copy.description, provider: { "@id": "https://in7ruder.com/#organization" }, url: localizedUrl(lang, "services/social-engineering-readiness"), areaServed: { "@type": "Country", name: "Switzerland" }, inLanguage: lang === "de" ? "de-CH" : "en-CH", category: "Cybersecurity" };
  return (
    <div id="main-content" lang={lang}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <section className="border-b border-[var(--line)] bg-[var(--paper)]"><div className="page-wrap py-16 md:py-24 lg:py-28"><p className="eyebrow">{copy.hero[0]}</p><h1 className="service-hero-title serif-display mt-8">{copy.hero[1]}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[var(--muted)] md:text-xl">{copy.hero[2]}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={`${base}/?service=social-engineering-readiness#contact`} className="button-primary">{copy.hero[3]} <Arrow /></Link><a href="#scope" className="button-secondary">{copy.hero[4]}</a></div><div className="mt-16 grid border-y border-[var(--line)] md:grid-cols-3">{copy.stats.map(([label, text], index) => <div key={label} className={`service-stat ${index > 0 ? "md:border-l md:border-[var(--line)] md:px-8" : "md:pr-8"}`}><p className="eyebrow">{label}</p><p className="mt-3 text-sm leading-6">{text}</p></div>)}</div></div></section>
      <section className="bg-[var(--ink)] text-white"><div className="page-wrap py-16 md:py-24"><div className="max-w-4xl"><p className="eyebrow eyebrow-dark">{copy.risk[0]}</p><h2 className="section-title serif-display mt-7">{copy.risk[1]}</h2><div className="mt-9 grid gap-6 border-t border-white/20 pt-8 text-base leading-8 text-white/70 md:grid-cols-2 md:gap-12 md:text-lg"><p>{copy.risk[2]}</p><p>{copy.risk[3]}</p></div></div></div></section>
      <section id="scope" className="bg-[var(--paper)]"><div className="page-wrap py-16 md:py-24"><header className="max-w-3xl"><p className="eyebrow">{copy.scope[0]}</p><h2 className="section-title serif-display mt-7">{copy.scope[1]}</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">{copy.scope[2]}</p></header><div className="mt-12 border-t border-[var(--ink)]">{copy.capabilities.map(([title, text]) => <article key={title} className="service-row"><h3 className="font-semibold">{title}</h3><p className="max-w-2xl text-base leading-7 text-[var(--muted)]">{text}</p></article>)}</div></div></section>
      <section className="border-y border-[var(--line)] bg-[var(--accent-soft)]"><div className="page-wrap py-16 md:py-24"><header className="max-w-3xl"><p className="eyebrow">{copy.formatsHeader[0]}</p><h2 className="section-title serif-display mt-7">{copy.formatsHeader[1]}</h2></header><div className="mt-12 grid border-y border-[var(--line)] md:grid-cols-3">{copy.formats.map(([title, text], index) => <article key={title} className={`py-8 md:min-h-64 md:px-8 ${index > 0 ? "border-t border-[var(--line)] md:border-l md:border-t-0" : "md:pl-0"}`}><h3 className="text-lg font-semibold">{title}</h3><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{text}</p></article>)}</div></div></section>
      <section className="bg-[var(--ink)] text-white"><div className="page-wrap py-16 md:py-24"><header className="max-w-3xl"><p className="eyebrow eyebrow-dark">{copy.method[0]}</p><h2 className="section-title serif-display mt-7">{copy.method[1]}</h2></header><div className="mt-12 border-t border-white/25">{copy.methodItems.map(([title, text]) => <article key={title} className="grid gap-3 border-b border-white/20 py-7 md:grid-cols-[18rem_1fr] md:gap-12"><h3 className="font-semibold">{title}</h3><p className="max-w-2xl text-sm leading-7 text-white/65">{text}</p></article>)}</div></div></section>
      <section className="bg-[var(--paper)]"><div className="page-wrap grid gap-10 py-16 md:py-24 lg:grid-cols-[0.65fr_1.35fr] lg:gap-20"><header><p className="eyebrow">{copy.faqHeader[0]}</p><h2 className="serif-display mt-7 text-4xl leading-tight md:text-5xl">{copy.faqHeader[1]}</h2></header><FAQAccordion items={copy.faqs} /></div></section>
      <section className="bg-[var(--accent)] text-white"><div className="page-wrap py-16 md:py-20"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-white/60">{copy.final[0]}</p><h2 className="serif-display mt-6 text-4xl leading-tight md:text-6xl">{copy.final[1]}</h2><Link href={`${base}/?service=social-engineering-readiness#contact`} className="accent-inverse-cta mt-8">{copy.final[2]} <Arrow /></Link></div></div></section>
    </div>
  );
}
